theme: jekyll-theme-minimal


title: Personal website
description: This is my personal website
And I would like to improve this [description](https://lauralorelei.github.io/hello-world/)
logo: 27319353197_34415d05a5_q.jpg
